/* OUPL data — generated by the editor. Safe to hand-edit.
   Format: one meet a year, classic only, best 5 lifters per school by DOTS. */

window.OUPL_DATA = {
  updated: "Sample data — not yet live",

  scoring: { countBestPerSchool: 5, requireFullTotal: true },

  schools: [
    { id:"yorku", name:"York University", short:"York", club:"Lions Strength", color:"#E31837", logo:"logos/yorku.png" },
    { id:"uoft", name:"University of Toronto", short:"Toronto", club:"U of T Powerlifting", color:"#2E4A8C", logo:"logos/uoft.png" },
    { id:"waterloo", name:"University of Waterloo", short:"Waterloo", club:"Waterloo Warriors Strength", color:"#F5C518", logo:"logos/waterloo.png" },
    { id:"mcmaster", name:"McMaster University", short:"McMaster", club:"McMaster Barbell", color:"#9B1B4E", logo:"logos/mcmaster.png" },
    { id:"queens", name:"Queen's University", short:"Queen's", club:"Queen's Powerlifting", color:"#C8102E", logo:"logos/queens.png" },
    { id:"ottawa", name:"University of Ottawa", short:"Ottawa", club:"uOttawa Power", color:"#A82234", logo:"logos/ottawa.png" },
    { id:"tmu", name:"Toronto Metropolitan", short:"TMU", club:"TMU Barbell", color:"#E8E8E8", logo:"logos/tmu.png" }
  ],

  editions: [
    { year:"2027", date:"2027-03-13", location:"Toronto, ON", host:"yorku" }
  ],

  results: [
    { year:"2027", lifter:"Avraham Sagi", school:"yorku", sex:"M", bodyweight:73.4, squat:202, bench:132, deadlift:235 }
  ]
};